### ISSUE TITLE
Tally cannot get the Tally Status for Camera in OBS

### ISSUE THREAD

**Issue by kevintokevinto** [josephdadams/TallyArbiter#665] opened 2024-03-12 13:56 UTC
### What happened?

I am using OBS 30.0.2 
websocket 5
I notice that if I select the source for a device in tally with a Video Capture Device.  
The tally data will show no busess 
the Program is always ON for those Video Capture Device
![image](https://github.com/josephdadams/TallyArbiter/assets/120235286/e453dbee-ec3f-4925-a063-ef1300c6714f)

However, if I select the source for a device in tally with a color source, the Program and Preview.

Moreover, I try to use OBS 27.0 with websocket 4,
I can have the Preview and Progam for a device in tally with a Video Capture Device.

So, I wonder if there is an issue with Tally Arbiter talking to websocket 5 with OBS.

### Version

3.0.8

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### If applicable, What Listener Clients are You Using?

Web (Microsoft Edge)

### TallyArbiter configuration

```javascript
{
  "security": {
    "jwt_private_key": "ZwqYDp9fgGg0DdI2Lt6FJPRVE2yPmAyBFm9LcBB5BHom0WlFp8dFdTViaDH6oa1u+w1X+f5Q1DcfRJ6/W51m66SIjF03DYVcbUO5aINa5XDCsoJgpNY8/YHxdnmxLE7in4pP9tIQlXwH7dVFOyJg5ZFW97aIBBG/UGFGqtg1Q0ss4aCde5LHf4gwlutTraV5lLTUVVOtdWy3Lh5AnNxTXab2dTUhoD2hcl/vFsuwB9Gf3UmO2amXphI366SAlH6HghhnNGyA0adGtygY4YKhEY/N8xwFkiQPs2eHN/Xc8xJtUR6M0yPcyX0am3dGdaPbrNBzuRU8gt0rtJ2fjcwwrA=="
  },
  "users": [
    {
      "username": "producer",
      "password": "$2a$10$R.uCO4j/DDqhKQXPeBE80ewBSDDAwwDaubA6Wzy3dSSKvtOkev3hS",
      "roles": "producer"
    },
    {
      "username": "admin",
      "password": "$2a$10$/L2C8hOvTVXm8DiIQIodtugWwRXPbK4VMHPBTC3vUi3R7ErZTox8a",
      "roles": "admin"
    }
  ],
  "cloud_destinations": [],
  "cloud_keys": [],
  "device_actions": [],
  "device_sources": [
    {
      "deviceId": "013ab2aa",
      "sourceIdx": "1",
      "address": "Facetime Camera",
      "sourceId": "75a6d04d",
      "id": "0a4a03bd"
    },
    {
      "deviceId": "9993a88c",
      "sourceIdx": "1",
      "address": "EpocCam",
      "sourceId": "75a6d04d",
      "id": "27d4cdd4"
    },
    {
      "deviceId": "6296ac7a",
      "sourceIdx": "1",
      "address": "Scene 3 - Color Block Yellow",
      "sourceId": "75a6d04d",
      "id": "0adbfd59"
    },
    {
      "deviceId": "490d030b",
      "sourceIdx": "1",
      "address": "Scene 2  - Color Block - Blue",
      "sourceId": "75a6d04d",
      "id": "58d03752"
    }
  ],
  "devices": [
    {
      "name": "Facetime Camera",
      "description": "Facetime Camera",
      "enabled": true,
      "id": "013ab2aa"
    },
    {
      "name": "Epoc Camera",
      "description": "Epoc Camera",
      "enabled": true,
      "id": "9993a88c"
    },
    {
      "name": "Scene - Yellow",
      "description": "Yellow",
      "enabled": true,
      "id": "6296ac7a"
    },
    {
      "name": "Scene - Blue",
      "description": "Blue",
      "enabled": true,
      "id": "490d030b"
    }
  ],
  "sources": [
    {
      "data": {
        "ip": "127.0.0.1",
        "port": 4444,
        "password": "<Secret>",
        "version": "5"
      },
      "name": "OBS-HOME",
      "sourceTypeId": "4eb73542",
      "reconnect": true,
      "enabled": true,
      "id": "75a6d04d",
      "max_reconnects": 5,
      "connected": true
    }
  ],
  "tsl_clients": [],
  "tsl_clients_1secupdate": false,
  "bus_options": [
    {
      "id": "e393251c",
      "label": "Preview",
      "type": "preview",
      "color": "#3fe481",
      "priority": 50
    },
    {
      "id": "334e4eda",
      "label": "Program",
      "type": "program",
      "color": "#e43f5a",
      "priority": 200
    },
    {
      "id": "12c8d699",
      "label": "Aux 1",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    },
    {
      "id": "12c8d689",
      "label": "Aux 2",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    }
  ],
  "externalAddress": "http://0.0.0.0:4455/#/tally",
  "remoteErrorReporting": false,
  "uuid": "34b52344"
}
```

### Relevant log output

```shell
Tally Data Output:
[3/12/24 9:50 PM] Source: OBS-HOME Address: 58d03752 No busses
[3/12/24 9:50 PM] Source: OBS-HOME Address: 0a4a03bd Bus: Program
[3/12/24 9:50 PM] Source: OBS-HOME Address: 27d4cdd4 Bus: Program
[3/12/24 9:50 PM] Source: OBS-HOME Address: 0adbfd59 No busses
[3/12/24 9:50 PM] Source: OBS-HOME Address: 58d03752 No busses
```

**Comment by Jocke4f** [comment] 2024-04-13 14:38
I tested with **TA v3.0.10** with **OBS v30.1.2** on Windows 10 with both with WebSocket 4.x and 5.x. I used the a usb web camera (WebC) and program/preview followed the status in OBS. I also tested with a BMD Intense Shuttle (BMD IS) and program/preview followed as expected. I don't seen any changes between TA v3.0.0 and v3.0.10 that would impact this.

This is how **Tally Data** looks for me:
```
[4/13/24 4:31 PM] OBS WebC Bus: Preview
[4/13/24 4:31 PM] OBS BMD IS None
[4/13/24 4:31 PM] OBS WebC Bus: Preview
[4/13/24 4:31 PM] OBS BMD IS Bus: Program
[4/13/24 4:32 PM] OBS WebC None
[4/13/24 4:32 PM] OBS BMD IS Bus: Preview
[4/13/24 4:32 PM] OBS WebC Bus: Program
[4/13/24 4:32 PM] OBS BMD IS Bus: Preview
```

Can you test with a later OBS version? There are changes in OBS in the websocket part between v30.0.2 and v30.1.2.

**Comment by Jocke4f** [comment] 2024-04-13 16:49
Now I understand the issue. If one in TA select the actual OBS source then it doesn't work. If one instead select the Scene in which the source is used then it works.

**Comment by Jocke4f** [comment] 2024-04-14 11:39
Based on a quick code inspection does it look as if when using Websocket 4 all the nested scenes and sources to a specific scene is handle when in preview or program. This is not done when using Websocket 5.

**Comment by Jocke4f** [comment] 2024-08-11 18:13
This is a duplicate of https://github.com/josephdadams/TallyArbiter/issues/527.

**Closed by Jocke4f** 2024-08-11 18:13 UTC
Labels: bug
