### ISSUE TITLE
[Bug]: Can't login to TallyArbiter

### ISSUE THREAD

**Issue by DiloMurphy** [josephdadams/TallyArbiter#571] opened 2023-06-25 15:09 UTC
### What happened?

admin,12345 will not work to login.

TA knows the password is correct but will just not enter into settings.

Running on an Raspberry Pi 2 

### Version

3.04

### Distribution

CLI

### OS

Linux

### What browsers are you seeing the problem on?

Chrome

### If applicable, What Listener Clients are You Using?

M5 Stick

### TallyArbiter configuration

```javascript
Can't get into settings!
```

**Comment by hrueger** [comment] 2023-07-08 08:16
Hi @DiloMurphy,
sorry for the late reply - life is pretty busy right now.
What do you mean by `TA knows the password is correct but will just not enter into settings.`? How do you know that TA knows that the password is correct?
Please also paste your configuration file, so we can try to reproduce this.

If you just rename the config file to something like `config.json.backup`, TA should recreate the config file. Does it work then?

**Comment by TychoCeltCast** [comment] 2023-07-16 08:32
> Hi @DiloMurphy, sorry for the late reply - life is pretty busy right now. What do you mean by `TA knows the password is correct but will just not enter into settings.`? How do you know that TA knows that the password is correct? Please also paste your configuration file, so we can try to reproduce this.
> 
> If you just rename the config file to something like `config.json.backup`, TA should recreate the config file. Does it work then?

I also had issues when switching versions; somewhere in the upgrade path it went wrong. I removed the config and it works again as expected.

**Comment by Jocke4f** [comment] 2024-01-10 15:54
Is this still an open issue?

**Comment by Jocke4f** [comment] 2024-01-18 16:20
I have tested both v3.0.4 and v3.0.7 freshly installed on a RPI 4 without being able to reproduce this. I had no problem logging in with the default admin account. If it is not possible to reproduce this do I suggest that we close this.

**Comment by DiloMurphy** [comment] 2024-01-18 17:08
Hold on I will try to send you a video recording of problem Forsberg ***@***.***> wrote:﻿
I have tested both v3.0.4 and v3.0.7 freshly installed on a RPI 4 without being able to reproduce this. I had no problem logging in with the default admin account. If it is not possible to reproduce this do I suggest that we close this.

**Comment by MatteoGheza** [comment] 2024-01-24 15:33
It seems to be unable to reproduce. Let me know if this is still an issue.
Thanks to everybody for the feedback.

**Closed by MatteoGheza** 2024-01-24 15:33 UTC
Labels: bug
