### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (readin...

### ISSUE THREAD

**Issue by soundman516** [josephdadams/TallyArbiter#706] opened 2024-07-24 14:05 UTC
### What happened?

Carbonite Ultra source doesnt work, i immediately start getting errors, when i switch my sources on the switcher. if any of my devices in tally arbiter are assigned to a carbonite ultra source this error occurs. the error goes away if i change to generic TSL3.1 in v3.0.8, but can't get carbonite ultra sources to function in v3.0.9 or 3.0.10 either.

### Version

3.0.8

### Distribution

Desktop

### OS

MacOS

### TallyArbiter configuration

```javascript
{
  "security": {
    "jwt_private_key": ""
  },
  "users": [],
  "device_actions": [],
  "device_sources": [
    {
      "deviceId": "270ccadc",
      "sourceIdx": "0",
      "address": "1",
      "bus": "onair",
      "sourceId": "44a57aae",
      "id": "dc6a61b4"
    },
    {
      "deviceId": "fb74f98b",
      "sourceIdx": "0",
      "address": "2",
      "bus": "onair",
      "sourceId": "44a57aae",
      "id": "266b0245"
    },
    {
      "deviceId": "10caf71d",
      "sourceIdx": "0",
      "address": "3",
      "bus": "onair",
      "sourceId": "44a57aae",
      "id": "745cc4e0"
    }
  ],
  "devices": [
    {
      "name": "CAM1",
      "tslAddress": 1,
      "enabled": true,
      "id": "270ccadc"
    },
    {
      "name": "CAM2",
      "tslAddress": 2,
      "enabled": true,
      "id": "fb74f98b"
    },
    {
      "name": "CAM3",
      "tslAddress": 3,
      "enabled": true,
      "id": "10caf71d"
    }
  ],
  "sources": [
    {
      "data": {
        "port": 9801,
        "transport_type": "udp"
      },
      "name": "Carb Ultra",
      "sourceTypeId": "7da3b524",
      "reconnect": true,
      "enabled": true,
      "id": "44a57aae",
      "max_reconnects": 5,
      "connected": true
    }
  ],
  "bus_options": [
    {
      "id": "e393251c",
      "label": "Preview",
      "type": "preview",
      "color": "#3fe481",
      "priority": 50
    },
    {
      "id": "334e4eda",
      "label": "Program",
      "type": "program",
      "color": "#e43f5a",
      "priority": 200
    },
    {
      "id": "12c8d699",
      "label": "Aux 1",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    },
    {
      "id": "12c8d689",
      "label": "Aux 2",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    }
  ],
  "externalAddress": "http://0.0.0.0:4455/#/tally",
  "remoteErrorReporting": false,
  "uuid": ""
}
```

### Relevant log output

```shell
[2024-07-24 10:01:43] info: Device Source Added: CAM3 - Carb Ultra
[2024-07-24 10:01:43] info: Config file saved to disk.
[2024-07-24 10:01:45] error: Caught exception: TypeError: Cannot read properties of undefined (reading 'find')
[2024-07-24 10:01:48] error: Caught exception: TypeError: Cannot read properties of undefined (reading 'find')
```

### Error stacktrace (if applicable)

```shell
TypeError: Cannot read properties of undefined (reading 'find')
    at _loop_2 (/Applications/TallyArbiter.app/Contents/Resources/app.asar/dist/sources/RossCarbonite.js:340:84)
    at _loop_1 (/Applications/TallyArbiter.app/Contents/Resources/app.asar/dist/sources/RossCarbonite.js:353:21)
    at RossCarboniteSource.updateRossCarboniteTallyData (/Applications/TallyArbiter.app/Contents/Resources/app.asar/dist/sources/RossCarbonite.js:367:13)
    at RossCarboniteSource.removeRossCarboniteTally (/Applications/TallyArbiter.app/Contents/Resources/app.asar/dist/sources/RossCarbonite.js:320:22)
    at RossCarboniteSource.processRossCarboniteTally (/Applications/TallyArbiter.app/Contents/Resources/app.asar/dist/sources/RossCarbonite.js:275:38)
    at tslumd.<anonymous> (/Applications/TallyArbiter.app/Contents/Resources/app.asar/dist/sources/RossCarbonite.js:233:23)
    at tslumd.emit (node:events:517:28)
    at Parser.<anonymous> (/Applications/TallyArbiter.app/Contents/Resources/app.asar/node_modules/tsl-umd/index.js:35:9)
    at Parser.parse (/Applications/TallyArbiter.app/Contents/Resources/app.asar/node_modules/packet/index.js:446:25)
    at Socket.<anonymous> (/Applications/TallyArbiter.app/Contents/Resources/app.asar/node_modules/tsl-umd/index.js:37:15)
```

**Comment by josephdadams** [comment] 2024-08-08 23:41
Dupe of #620

**Closed by josephdadams** 2024-08-08 23:41 UTC
Labels: bug
