### ISSUE TITLE
[Bug]: Connected Listeners Do Not Appear in UI

### ISSUE THREAD

**Issue by MaxPerryCode** [josephdadams/TallyArbiter#149] opened 2021-08-05 22:07 UTC
### What happened?

I have a number of devices connected, however they are not appearing in the Settings, Connected Listeners list within the UI. Any ideas? 
![Ally Arbiter Connected Listeners Missing](https://user-images.githubusercontent.com/78985740/128427366-c95871e4-f4cc-4055-b52a-99361ce0f146.PNG)

### Version

2.0.6

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
[8/5/21 11:37 PM] VMix Emulator Connection ::ffff:10.251.105.105:52709 unsubscribed to tally
[8/5/21 11:37 PM] VMix Emulator Connection from ::ffff:10.251.105.105:52709 closed
[8/6/21 12:37 AM] Inactive Client removed: 9182bc88
[8/6/21 7:00 AM] New VMix Emulator Connection from ::ffff:10.251.105.102:63329
[8/6/21 7:00 AM] VMix Emulator Connection ::ffff:10.251.105.102:63329 subscribed to tally
[8/6/21 7:49 AM] Listener Client Connected. Type: web Device: CAM3
[8/6/21 7:55 AM] Listener Client Connected. Type: web Device: CAM2
[8/6/21 8:04 AM] Listener Client Connected. Type: web Device: CAM1
```

**Comment by JTF4** [comment] 2021-08-05 22:17
You're trying to connect with a phone, right?

**Comment by MaxPerryCode** [comment] 2021-08-05 22:23
> You're trying to connect with a phone, right?

Testing with Chrome browser on Windows 10.

**Comment by JTF4** [comment] 2021-08-06 00:55
Ok. Met me do some quick research on my end and I'll see what's happening.

**Comment by JTF4** [comment] 2021-08-06 02:42
If you are still running version 2.0.6, I would recommend updated to 2.0.8 to see if it fixes your problem. I should have thought about that at the very beginning. 

If that still does not help, then please upload your config.json file so I can replicate your setup exactly.

**Comment by josephdadams** [comment] 2021-08-06 03:17
Do they show up if you refresh the UI page?

**Comment by MaxPerryCode** [comment] 2021-08-06 06:13
Upgraded to 2.0.8. Tally Web Clients now appear, however what seems to be happening is when the Vmix client connects, Tally Arbiter no longer list any new connected listeners. Seems the issue is related to the Vmix connected Talley.

**Comment by JTF4** [comment] 2021-08-06 17:22
Interesting. Can you upload your config.json file?

**Comment by MaxPerryCode** [comment] 2021-08-10 10:56
Apologies for what must be dumb issue. I can't seem to be able to locate my config.json file. I don't seem to have a TallyArbiter directory within usr/local/share/

I'm running Ubuntu OS. Tally Arbiter was installed via download the source code and running npm install

Any ideas?

**Comment by josephdadams** [comment] 2021-08-10 19:21
It should be in your home folder. `~/.local/share/TallyArbiter/`.

**Comment by MaxPerryCode** [comment] 2021-08-11 12:53
[config.zip](https://github.com/josephdadams/TallyArbiter/files/6968508/config.zip)
Thank you for the tip. config.json attached.

**Comment by JTF4** [comment] 2021-08-15 13:35
You are using a vMix listener client, right? After connecting one to my instance of TA I still see all of my clients.

Would you mind updating to 2.0.11 if you have not already? I'm curious to see if it makes a difference as we did make a slight chance to the listener client connection code in our updates.

**Comment by MaxPerryCode** [comment] 2021-08-16 04:31
Thanks again for looking into this. Upgraded to v2.0.11, unfortunately this has not resolved the issue. I'm suing the Vmix listener by Thomas Mout, located here: https://github.com/ThomasMout/Arduino-vMix-tally Hope this helps.

**Comment by josephdadams** [comment] 2021-08-16 10:32
Do the listeners show up if you refresh the page? Or reload it, close the window and re open, etc.

**Comment by MaxPerryCode** [comment] 2021-08-17 10:47
Unfortunately no - once the vmix listener is connected no listeners are displayed. For example, connect the vmx listener and then connect a web listener, no listeners are displayed. If I remove the vmix listener and leave the web listener connected, once the Tally Arbiter disconnects the vmix listener (I'm assuming the connection times out) the web listener appears.

**Comment by josephdadams** [comment] 2021-08-17 13:09
I think I know why this is happening. So VMix tally clients that connect to TA, thinking that TA is actually a VMix server - when they connect, they do not explicitly say "I want to listen to tally from device 1" or whatever. They just say "subscribe tally", and the TA server sends them the tally data for all the inputs. This is how VMix tally works. Then on the client end, you've got it configured to use input 1, 2, etc.

So when a VMix emulator client connects, it is added to the list of listener clients with a device ID of `null`. The problem is that the UI cannot handle this properly and I believe it is erroring out, which is why you don't see any of them listed when those clients are present.

I will work on a solution and report back when I have something for you to test.

**Comment by josephdadams** [comment] 2021-08-18 12:56
#170 handles this, when it is merged you can upgrade.

**Comment by JTF4** [comment] 2021-08-18 16:46
Just merged #170 I will draft a new release and once you upgrade your issue should be fixed

**Comment by JTF4** [comment] 2021-08-18 17:39
Please update to the newest version of TallyArbiter. Once you do that it should fix your problem!

Please feel free to reopen the issue if the problem persists after upgrading to 2.0.13

**Closed by JTF4** 2021-08-18 17:39 UTC
Labels: bug, in progress

**Comment by MaxPerryCode** [comment] 2021-08-19 10:11
Will test and report back - thank you.
